// Deterministic, local motion studies. No Chrome APIs, saved notes, or accounts touched.
const config=new URLSearchParams(location.search),kind=config.get('clip')||'annotate';
const portrait=['live-page','purpose','preview'].includes(kind),W=portrait?864:1440,H=portrait?1080:810;
const stage=document.querySelector('#stage');stage.className=portrait?'portrait':'';stage.style.transform=`scale(${innerWidth/W})`;
const colors=['#EDDDB6','#C2E9CE','#BCE5FF','#FED4BE','#E6D5FC','#FCD0E3'];
const noteText='Give this headline a little more breathing room.';
const folderSVG='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linejoin="round"><path d="M3 6a2 2 0 0 1 2-2h4l3 3h7a2 2 0 0 1 2 2v10H3Z"/><path d="M12 10v6m-3-3h6"/></svg>';
const penSVG='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M13 4H5a2 2 0 0 0-2 2v13h16v-8M9 15l1-5L19 1l4 4-9 9Z"/></svg>';
const logo='<img src="images/icon-128.png">';
const arrow='<svg width="30" height="36" viewBox="0 0 25 30"><path d="M3 2v23l6-6 5 9 4-2-5-9h9Z" fill="#202124" stroke="white" stroke-width="1.4" stroke-linejoin="round"/></svg>';
const pencil='<svg width="36" height="36" viewBox="0 0 32 32"><path d="M5 26l2-8L21 4a3 3 0 0 1 4 0l3 3a3 3 0 0 1 0 4L14 25l-9 2Z" fill="#202124" stroke="white" stroke-width="1.3"/><path d="m8 18 6 6M20 6l6 6M6 25l4-1" stroke="white" fill="none"/></svg>';
const clamp=n=>Math.max(0,Math.min(1,n)),ease=n=>{n=clamp(n);return n*n*(3-2*n)},lerp=(a,b,t)=>a+(b-a)*ease(t);
const typed=(s,t,start,dur)=>s.slice(0,Math.floor(s.length*clamp((t-start)/dur)));
const entry=(t,start)=>`opacity:${ease((t-start)/.25)};transform:translateY(${12*(1-ease((t-start)/.25))}px)`;
function web(s){if(portrait)return webTwo(s);return `<div class="site" style="right:${s.panel&&!s.full?355:0}px"><div class="webcontent" style="transform:translateY(-${s.scroll||0}px)"><div class="nav"><div class="figma"><svg viewBox="0 0 38 57"><path fill="#f24e1e" d="M9.5 0h9.5v19H9.5a9.5 9.5 0 0 1 0-19"/><path fill="#ff7262" d="M19 0h9.5a9.5 9.5 0 0 1 0 19H19"/><path fill="#a259ff" d="M9.5 19H19v19H9.5a9.5 9.5 0 0 1 0-19"/><circle cx="28.5" cy="28.5" r="9.5" fill="#1abcfe"/><path fill="#0acf83" d="M9.5 38H19v9.5a9.5 9.5 0 1 1-9.5-9.5"/></svg>figma</div><span id="products" class="${s.menu?'reactive':''}">Products⌄</span><span>Solutions</span><span>Community</span><b>Get started</b></div><div class="hero"><h1 id="target" class="${s.selected?'selected '+s.color:''}">The full-stack<br>creative canvas</h1><div id="cta" class="cta ${s.hoverCTA?'hover':''} ${s.pickCTA?'pick-hover':''}">Get started →</div></div><div class="tiles">${['Design','Build','Collaborate'].map((x,i)=>`<div id="tile${i}" class="tile ${s.hoverTile===i?'hover':''} ${s.pickTile&&i===1?'pick-hover':''}"><div class="shape"></div><strong>${x}</strong></div>`).join('')}</div><section class="section"><h2 class="${s.allNotes&&kind!=='preview'?'selected mint':''}" id="section-target">One workspace for your entire product development process.</h2><p>Made so your whole team can go from WIP to ship, together.</p></section><section class="section last"><h2 class="${s.allNotes&&kind!=='preview'?'selected sky':''}">Powerfully expressive.<br>Incredibly precise.</h2><p>Every technical tool you need to dial in the details.</p></section></div>${s.menu?'<div class="menu"><div><small>CREATE</small><span>Figma Design</span><span>Figma Draw</span><span>Figma Slides</span></div><div><small>BUILD</small><span>Figma Make</span><span>Dev Mode</span><span>Figma Sites</span></div></div>':''}</div>`}
// Simplified public 2x4.org homepage, retaining the existing demo target positions.
function webTwo(s){return `<div class="site twofour"><div class="webcontent" style="transform:translateY(-${s.scroll||0}px)"><div class="nav"><div class="two-logo">2×4</div><span>About</span><span>News</span><span>Search</span></div><div class="hero"><h1 id="target" class="${s.selected?'selected '+s.color:''}">Design brands<br>Visualize strategy<br>Tell stories</h1><div class="categories"><span id="cta" class="${s.pickCTA?'pick-hover':''}">Featured</span><span>Client</span><span>Sector</span><span>Service</span><span>All</span></div></div><div class="tiles">${['REINVENTION','Artisan Now','Culture Push'].map((text,i)=>`<div id="tile${i}" class="tile ${s.pickTile&&i===1?'pick-hover':''}"><strong>${text}</strong><small>${['FONDAZIONE PRADA','GINORI 1735','INSTAGRAM'][i]}</small></div>`).join('')}</div><section class="section"><h2 id="section-target" class="${s.allNotes&&kind!=='preview'?'selected mint':''}">Articulate values.<br>Provoke response.</h2><p>2×4 — Featured work</p></section><section class="section last"><h2 class="${s.allNotes&&kind!=='preview'?'selected sky':''}">Look closely.<br>Rethink systems.</h2><p>Design brands. Activate space.</p></section></div></div>`}
const datasets={Design:[['Figma — The creative canvas',[noteText,'Keep this interaction as a reference.']],['Sooim Kang · Portfolio',['Make the project titles easier to scan.']]],Research:[['A guide to thoughtful interfaces',['Useful examples for the next critique.','Check the original source for this claim.','Compare the spacing in these examples.']]],Inspiration:[['Sooim Kang · Portfolio',['Keep this introduction short.','Love the rhythm between projects.']],['Figma — The creative canvas',['Notice the balance of type and space.']],['A guide to thoughtful interfaces',['Clear focus states are worth keeping.']]]};
datasets.All=[];for(const group of [datasets.Design,datasets.Research,datasets.Inspiration]){for(const [name,notes] of group){let page=datasets.All.find(p=>p[0]===name);if(!page){page=[name,[]];datasets.All.push(page)}page[1].push(...notes)}}
function panel(s){let data=kind==='annotate'?[["Figma — The creative canvas",[noteText]]]:datasets[s.filter||'All'];return `<aside class="panel ${s.full?'full':''}" style="${s.panelBorn?entry(s.t,s.panelBorn):''}"><div class="brand">${logo}Notate<em>×</em></div><div class="panel-head"><strong>Notes</strong><span class="clear">Clear all</span><div id="new" class="button">${penSVG}New</div></div><div class="filters">${['All','Design','Research','Inspiration'].map((x,i)=>`<span id="filter${i}" class="pill ${['','yellow','sky','mint'][i]} ${s.filter===x?'selected':''}">${x}</span>`).join('')}</div>${s.empty?'<p style="color:#888;font-size:14px;padding:5px">No saved notes yet</p>':data.map(([name,notes],i)=>`<div class="page-row"><span id="page${i}" class="page-link"><span>◎</span> ${portrait?name.replace('Figma — The creative canvas','2×4 — Featured work'):name}</span><span id="drop${i}" class="page-count"><small>${notes.length}</small><span class="chevron">${s.open.includes(i)?'⌃':'⌄'}</span></span></div><div class="children" style="max-height:${s.open.includes(i)?300:0}px">${notes.map((n,j)=>`<div id="row${i}${j}" class="note-row ${s.hoverRow===`${i}${j}`?'hover':''}"><span>${n}</span><i class="marker" style="background:${kind==='annotate'?'transparent':datasets.Research.some(p=>p[1].includes(n))?colors[2]:datasets.Inspiration.some(p=>p[1].includes(n))?colors[1]:colors[0]}"></i></div>`).join('')}</div>`).join('')}</aside>`}
function composer(s){return `<div class="scrim" style="opacity:${s.noScrim?0:1}"></div><div class="composer" style="${s.composerBorn?entry(s.t,s.composerBorn):''};${s.tint?'background:'+s.tint:''}">${s.folder?`<div class="folder-form"><div class="input" aria-label="Folder name">${s.folderName||''}<span class="caret"></span></div><label>Color</label><div class="swatches">${colors.map((c,i)=>`<div id="swatch${i}" class="swatch ${s.swatch===i?'on':''}" style="background:${c}"></div>`).join('')}</div><div class="actions"><span>Back</span><span id="folder-save" class="button">Save</span></div></div>`:`<div class="draft">${s.text||''}${s.typing?'<span class="caret"></span>':''}</div><div class="chooser">${!s.assigned?`<span id="folder-plus" class="folder-plus">${folderSVG}</span>`:''}${s.choices?['Design','Research','Inspiration'].map((x,i)=>`<span id="choice${i}" class="pill ${['yellow','sky','mint'][i]}" style="${s.choice===i?'background:'+colors[[0,2,1][i]]:''}">${x}</span>`).join(''):s.assigned?`<span class="pill assigned-folder">${s.folderLabel||'Design'}${kind==='purpose'?`<span id="folder-remove" class="folder-remove" style="opacity:${s.removeVisible?1:0}">×</span>`:''}</span>`:''}</div><div class="actions"><span>Cancel</span><span id="save" class="button">Save <kbd>⌘ ↵</kbd></span></div>`}</div>`}
function render(t){let s={t,panel:!portrait,open:[],filter:'All',color:'neutral',text:noteText,selected:false},steps=[],clicks=[],keys=[],mode='arrow',duration=durations[kind];
if(kind==='annotate'){s.empty=t<10;s.selected=t>=3;s.color='neutral';s.noteColor='#F7F7F5';s.composer=t>=4&&t<10;s.composerBorn=4;s.text=typed(noteText,t,4.7,3);s.typing=t>=4.7&&t<8.6;s.note=t>=10;s.open=t>=10?[0]:[];s.toolbar=t>=1.6;s.noteBorn=10;steps=[[0,'Click New'],[2.6,'Choose an element on the page'],[4,'Write your thought'],[10,'Keep it in context']];keys=[[0,1080,440],[1.2,'new'],[2,'new'],[3,'target'],[4,'target'],[4.6,425,355],[8.6,425,355],[9.7,'save'],[10.3,780,490],[13,780,490]];clicks=[1.6,3.6,9.8];mode=t>2&&t<4?'pencil':'arrow'}
if(kind==='organize'){s.selected=true;s.composer=t<11;s.folder=t>=2.4&&t<8;s.folderName=typed('Design',t,3.1,1.4);s.swatch=t>=6?0:-1;s.assigned=t>=8;s.color=t>=8?'yellow':'neutral';s.tint=t>=8&&t<11?colors[0]:'';s.note=t>=11;s.noteBorn=11;s.open=t>=11?[0]:[];s.filter=t>=11?'Design':'All';s.empty=t<11;s.noteX=lerp(470,590,(t-13.2)/.9);s.noteY=lerp(220,360,(t-13.2)/.9);steps=[[0,'Create a folder from your note'],[2.4,'Give it a purpose and a color'],[8,'Save the note to Design'],[12,'Drag the note to reposition it']];keys=[[0,500,360],[1.8,368,530],[2.8,368,530],[3.1,430,355],[4.8,430,355],[5.7,368,423],[6.5,368,423],[7.6,690,492],[8.6,690,492],[9.5,690,587],[10.8,690,587],[12.1,690,587],[13.2,650,390],[14.1,770,530],[18,770,530]];clicks=[2.2,6,7.9,10.8];mode=t>=3.1&&t<4.8?'typing':'arrow';s.assigned=t>=8;s.dragging=t>=13.2&&t<14.1}
if(kind==='return'){s.newtab=t>=1.5&&t<8.5;s.tab=t>=1.5;s.panel=t>=4;s.panelBorn=4;s.open=t>=5.8?[0]:[];s.hoverRow=t>=7?'00':'';s.selected=t>=8.5;s.color='yellow';s.note=t>=8.5;s.scroll=t>=8.5?lerp(420,0,(t-8.5)/1.5):0;s.noteY=220-s.scroll;s.noteBorn=8.5;steps=[[0,'Open a new tab'],[3.4,'Open Notate'],[5.4,'Preview your saved note'],[8.5,'Return to the page and its original context']];keys=[[0,650,480],[1.2,'plus'],[2.3,600,450],[3.5,'extension'],[4.5,'extension'],[5.5,'drop0'],[6.4,'drop0'],[7.7,'row00'],[16,'row00']];clicks=[1.4,3.9,5.8,8.3]}
if(kind==='live-page'){s.panel=false;s.toolbar=true;s.newTool=true;s.picking=t>=1.5;s.loading=t<1;s.selected=t>=2.1&&t<3.1;s.color='neutral';s.pickCTA=t>=3.6&&t<4.6;s.pickTile=t>=5.1;keys=[[0,520,300],[1.1,'toolbar-new'],[1.5,'toolbar-new'],[2.1,'target'],[3.1,'target'],[3.6,'cta'],[4.6,'cta'],[5.1,'tile1'],[6.9,'tile1']];clicks=[1.4];mode=t>=1.5?'pencil':'arrow'}
if(kind==='purpose'){s.panel=false;s.selected=true;s.color='neutral';s.composer=t<12;s.noScrim=true;s.choice=t>=1.5&&t<3?0:t>=4&&t<5.5?1:t>=6.5&&t<8?2:t>=9?0:-1;s.choices=s.choice<0;s.assigned=s.choice>=0;s.folderLabel=['Design','Research','Inspiration'][s.choice];s.tint=s.choice<0?'#F7F7F5':colors[[0,2,1][s.choice]];s.removeVisible=(t>=2.2&&t<3)||(t>=4.7&&t<5.5)||(t>=7.2&&t<8);s.panel=t>=12;s.full=true;s.open=[0,1,2];s.filter=t>=21?'Inspiration':t>=18?'Research':t>=15?'Design':'All';s.panelBorn=12;keys=[[0,420,570],[1.3,286,590],[1.8,286,590],[2.5,270,578],[3.3,270,578],[3.8,390,590],[4.3,390,590],[5,280,578],[5.8,280,578],[6.3,495,590],[6.8,495,590],[7.5,297,578],[8.3,297,578],[8.8,286,590],[9.5,286,590],[10.8,610,630],[12.5,610,630],[14.8,'filter1'],[16,'filter1'],[17.8,'filter2'],[19,'filter2'],[20.8,'filter3'],[23.9,'filter3']];clicks=[1.5,3,4,5.5,6.5,8,9,11.7,15,18,21]}
if(kind==='preview'){s.panel=t<10;s.full=true;s.open=t>=5?[0,1]:t>=2?[0]:[];s.hoverRow='';s.selected=t>=10;s.color='yellow';s.note=t>=10;s.allNotes=t>=10;s.scroll=t<10?0:t<13?lerp(250,0,(t-10)/1.3):t<18?lerp(0,540,(t-13)/3):lerp(540,890,(t-18)/3);s.noteY=220-s.scroll;s.noteBorn=10;steps=[[0,'Preview before opening'],[2,'Expand notes on one page'],[5,'Compare another page'],[9,'Jump to the saved thought'],[13,'Browse and scroll with your notes'],[18,'Notes stay beside their elements']];keys=[[0,680,600],[.7,'page0'],[1.2,'page0'],[1.6,'drop0'],[3.2,'row00'],[3.8,'page1'],[4.2,'page1'],[4.6,'drop1'],[6.2,'row10'],[7.8,'row00'],[9.4,'row00'],[11,690,510],[14,700,700],[22,700,750]];clicks=[1.9,4.9,9.6]}
const caption=steps.filter(x=>x[0]<=t).at(-1)?.[1]||'';
stage.innerHTML=`<div class="browser"><div class="chrome"><div class="tabs"><i class="dot"></i><i class="dot"></i><i class="dot"></i><div class="tab">${portrait?'2×4 — Featured work':'Figma — The creative canvas'}</div>${s.tab?'<div class="tab">New tab</div>':''}<span id="plus" class="plus">+</span></div><div class="address-row"><span style="font-size:15px;color:#888">← &nbsp; →</span><div class="address">${s.newtab?'Search or enter a URL':portrait?'2x4.org':'figma.com'}</div><span id="extension">${logo}</span></div></div><div class="viewport">${web(s)}${s.loading?`<div style="position:absolute;inset:0;background:white;z-index:19;opacity:${1-ease((t-1.2)/.5)}"></div><div class="loading" style="width:${clamp(t/1.7)*100}%"></div>`:''}${s.newtab?'<div class="newtab"><h2>New tab</h2><div class="search">Search or enter a URL</div></div>':''}${s.note?`<div id="saved-note" class="note" style="background:${s.noteColor||colors[0]};border-color:${s.noteColor?'#b5b5af':'#DDCDA9'};left:${s.noteX||470}px;top:${s.noteY??220}px;${entry(t,s.noteBorn||0)}">${noteText}</div>`:''}${s.allNotes?`<div class="note" style="background:${colors[1]};border-color:#B0D5EB;left:400px;top:${790-s.scroll}px">Useful structure for the project page.</div><div class="note" style="background:${colors[2]};border-color:#B0D5EB;left:360px;top:${1160-s.scroll}px">Keep this interaction as a reference.</div>`:''}${s.panel?panel(s):''}${s.toolbar?`<div class="toolbar ${s.panel?'':'no-panel'}"><span style="padding-left:8px;color:#888">Clear all</span><span class="done">Done <small>Esc</small></span>${s.newTool?`<span id="toolbar-new" class="button">${penSVG}New</span>`:''}</div>`:''}${s.composer?composer(s):''}</div></div>`;
if(kind==='preview'&&t>=10){
const content=document.querySelector('.webcontent'),viewport=document.querySelector('.viewport');
const maxScroll=Math.max(0,content.offsetHeight-viewport.clientHeight);
const excess=Math.max(0,s.scroll-maxScroll);
if(excess){content.style.transform=`translateY(-${maxScroll}px)`;for(const note of document.querySelectorAll('.viewport>.note'))note.style.top=`${parseFloat(note.style.top)+excess}px`;}
}
if(kind==='preview'&&t>=10&&t<12){const target=document.getElementById('target');const pulse=Math.pow(Math.sin(Math.PI*(t-10)),2);target?.style.setProperty('background-color',`color-mix(in srgb, #EDDDB6 ${Math.round(22+65*pulse)}%, white)`,'important')}
function pos(k){if(typeof k[1]==='number')return [k[1]-(portrait?42:70),k[2]-(portrait?100:65)];let el=document.getElementById(k[1]);if(!el)return [W*.7,H*.55];let r=el.getBoundingClientRect(),scale=innerWidth/W;return [(r.left+r.width*.7)/scale,(r.top+r.height*.65)/scale]}
let a=keys[0],b=keys.at(-1);for(let n=1;n<keys.length;n++){if(t<=keys[n][0]){a=keys[n-1];b=keys[n];break}}let p=pos(a),q=pos(b),f=(t-a[0])/(b[0]-a[0]||1),x=lerp(p[0],q[0],f),y=lerp(p[1],q[1],f);let cursor=document.createElement('div');cursor.className='cursor';cursor.style.cssText=`left:${x}px;top:${y}px`;cursor.innerHTML=mode==='pencil'?pencil:arrow;if(mode==='typing')cursor.style.opacity=0;stage.append(cursor);if(s.panel){for(const el of document.querySelectorAll('.page-link,.page-count,.note-row')){const r=el.getBoundingClientRect(),scale=innerWidth/W;if(x*scale>=r.left&&x*scale<=r.right&&y*scale>=r.top&&y*scale<=r.bottom)el.classList.add('hover')}}for(const ct of clicks){if(t>=ct&&t<ct+.4){let r=document.createElement('div');r.className='click';let v=(t-ct)/.4;r.style.cssText=`left:${x-18}px;top:${y-18}px;transform:scale(${.5+v});opacity:${1-v}`;stage.append(r)}}
stage.style.opacity=t<.4?ease(t/.4):t>duration-.5?1-ease((t-duration+.5)/.5):1;
}
const durations={annotate:14,organize:18,return:16,'live-page':7,purpose:24,preview:24};
window.renderFrame=render;window.clipDuration=durations[kind];render(0);
if(!config.has('render')){let start=performance.now();function play(now){render(((now-start)/1000)%durations[kind]);requestAnimationFrame(play)}requestAnimationFrame(play)}
